name: github deploy aws-ec2 integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/apps
            touch victory.txt

# name: Push-to-EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy to EC2
#     runs-on: ubuntu20.04

#   steps:
#     - name: Checkout the files
#       uses: actions/checkout@v2

#     - name: Deploy to Server 1
#       uses: easingthemes/ssh-deploy@main
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
#         REMOTE_HOST: ${{ secrets.HOST_DNS }}
#         REMOTE_USER: ${{ secrets.USERNAME }}

